services: 

  notebook_server:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    command: /app/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    restart: always
    ports: 
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - type: volume
        source: mongodb_data
        target: /data/db
    networks:
      notebook_network:

  mongo-express:
      image: mongo-express
      container_name: mongo-express
      restart: always
      ports:
        - "8081:8081"
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: password
        ME_CONFIG_MONGODB_SERVER: mongodb
      networks:
        notebook_network:
      depends_on:
        - mongodb

volumes:
  mongodb_data:

networks:
  notebook_network:
